apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: broker-failure-experiment
  namespace: default
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      tier: messaging
  scheduler:
    cron: "@every 3m"

