apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: database-failure-experiment
  namespace: default
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: postgresql
  scheduler:
    cron: "@every 5m"

